routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route for MiddleWare
Route::group(['middleware' => ['studentSession']], function () {
    Route::match(['get','post'], 'account','StudentController@account');
    Route::match(['get','post'], 'student-biodata','StudentController@studentBiodata');
    Route::match(['get','post'], 'student-choose-course','StudentController@studentChooseCourse');
    Route::match(['get','post'], 'student-lecture-calendar','StudentController@studentLectureCalendar');
    Route::match(['get','post'], 'student-lecture-activity','StudentController@studentLectureActivity');
    Route::match(['get','post'], 'student-exam-marks','StudentController@studentExamMarks');

    Route::match(['get','post'], 'verify-password','StudentController@verifyPassword');
    Route::match(['get','post'], 'student-update-password','StudentController@updatePassword');

});

//Route for Login
Route::get('/student','StudentController@studentLogin');
Route::get('/logout','StudentController@studentLogout');


Route::post('student-login', 'StudentController@LoginStudent');

//Route for Forgot Password
Route::get('student-forgot-password', 'StudentController@getForgotPassword');
Route::post('forgot-password', 'StudentController@ForgotPassword');


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->middleware('verified');

// Auth::routes();

// Route::get('/home', 'HomeController@index');

Route::resource('classes', 'ClassesController');

Route::resource('classrooms', 'ClassroomsController');

Route::resource('levels', 'LevelsController');

Route::resource('batches', 'BatchController');

Route::resource('shifts', 'ShiftController');

Route::resource('courses', 'CourseController');

Route::resource('faculties', 'FacultyController');

Route::resource('times', 'TimeController');

Route::resource('attendances', 'AttendanceController');

Route::resource('academics', 'AcademicController');

Route::resource('days', 'DayController');

Route::resource('classAssignings', 'ClassAssigningController');

Route::resource('classSchedulings', 'ClassSchedulingController');

Route::resource('transactions', 'TransactionController');

Route::resource('admissions', 'AdmissionController');

Route::resource('teachers', 'TeacherController');

Route::resource('roles', 'RoleController');

Route::resource('users', 'UserController');

Route::resource('semesters', 'SemesterController');

Route::resource('classSchedulings', 'ClassSchedulingController');

//route for dynamic selection
Route::get('/dynamicLevel', [
    'as' => 'dynamicLevel',
    'uses' => 'ClassSchedulingController@dynamicLevel'
    ]);

Route::resource('departments', 'DepartmentController');

Route::post('/insert', array('as' => 'insert', 'uses' => 'ClassAssigningController@insert'));


Route::resource('statuses', 'StatusesController');

//Multiple Language
Route::get('locale/{locale}', 'StudentController@languages');



// EMPLOYEE ROUTE
Route::get('/emp', 'EmployeeController@showEmployees');
Route::get('/emp/pdf','EmployeeController@createPDF');

app/Models/ClassScheduling.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class ClassScheduling
 * @package App\Models
 * @version September 3, 2020, 12:57 pm UTC
 *
 * @property integer $course_id
 * @property integer $class_id
 * @property integer $level_id
 * @property integer $shift_id
 * @property integer $classroom_id
 * @property integer $batch_id
 * @property integer $day_id
 * @property integer $time_id
 * @property integer $semester_id
 * @property string $start_date
 * @property string $end_date
 * @property boolean $status
 */
class ClassScheduling extends Model
{
    use SoftDeletes;

    public $table = 'class_schedulings';

    protected $primaryKey = 'schedule_id';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'course_id',
        'class_id',
        'level_id',
        'shift_id',
        'classroom_id',
        'batch_id',
        'day_id',
        'time_id',
        'semester_id',
        'start_date',
        'end_date',
        'status'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'schedule_id' => 'integer',
        'course_id' => 'integer',
        'class_id' => 'integer',
        'level_id' => 'integer',
        'shift_id' => 'integer',
        'classroom_id' => 'integer',
        'batch_id' => 'integer',
        'day_id' => 'integer',
        'time_id' => 'integer',
        'semester_id' => 'integer',
        'start_date' => 'date',
        'end_date' => 'date',
        'status' => 'boolean'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'course_id' => 'required|integer',
        'class_id' => 'required|integer',
        'level_id' => 'required|integer',
        'shift_id' => 'required|integer',
        'classroom_id' => 'required|integer',
        'batch_id' => 'required|integer',
        'day_id' => 'required|integer',
        'time_id' => 'required|integer',
        'semester_id' => 'required|integer',
        'start_date' => 'required',
        'end_date' => 'required',
        'status' => 'required|boolean',
        'deleted_at' => 'nullable',
        'created_at' => 'nullable',
        'updated_at' => 'nullable'
    ];

    
}

app/Http/Controllers/ClassSchedulingController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateClassSchedulingRequest;
use App\Http\Requests\UpdateClassSchedulingRequest;
use App\Repositories\ClassSchedulingRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;
use App\models\Batch;
use App\models\Classes;
use App\models\Classrooms;
use App\models\Course;
use App\models\Day;
use App\models\Levels;
use App\models\Semester;
use App\models\Shift;
use App\models\Time;
use DB;

class ClassSchedulingController extends AppBaseController
{ 
    /** @var  ClassSchedulingRepository */
    private $classSchedulingRepository;

    public function __construct(ClassSchedulingRepository $classSchedulingRepo)
    {
        $this->classSchedulingRepository = $classSchedulingRepo;
    }

    /**
     * Display a listing of the ClassScheduling.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $batch = Batch::all();
        $class = Classes::all();
        $classrooms = Classrooms::all();
        $course = Course::all();
        $day = Day::all();
        $level = Levels::all();
        $semester = Semester::all();
        $shift = Shift::all();
        $time = Time::all();

        // dd($batch);
        // dd($class); 
        // dd($course); 
        // dd($day); 
        // dd($level); 
        // dd($semester); 
        // dd($shift); 
        // dd($time); 

        $classSchedulings = $this->classSchedulingRepository->all();

        $classshedule = DB::table('class_schedulings')->select(
                                'courses.*',
                                'levels.*',
                                'days.*',
                                'batches.*',
                                'semesters.*',
                                'classes.*',
                                'shifts.*',
                                'times.*',
                                'classrooms.*',
                                'class_schedulings.*'
                                )
                                ->whereNull('class_schedulings.deleted_at')
                                ->join('courses','courses.course_id', '=', 'class_schedulings.course_id') 
                                ->join('batches','batches.batch_id', '=', 'class_schedulings.batch_id')
                                ->join('classes','classes.class_id', '=', 'class_schedulings.class_id')
                                ->join('days','days.day_id', '=', 'class_schedulings.day_id')
                                ->join('levels','levels.id', '=', 'class_schedulings.level_id')
                                ->join('semesters','semesters.semesters_id', '=', 'class_schedulings.semester_id')
                                ->join('shifts','shifts.shift_id', '=', 'class_schedulings.shift_id')
                                ->join('times','times.time_id', '=', 'class_schedulings.time_id')
                                ->join('classrooms','classrooms.classroom_id', '=', 'class_schedulings.classroom_id')
                                ->get();
                                //dd($classshedule); die;

        return view('class_schedulings.index', compact('classshedule','batch','class','classrooms','course','day','level','semester','shift','time'))
            ->with('classSchedulings', $classSchedulings);
    }

    public function dynamicLevel(Request $request)
    {
        $course_id = $request->get('course_id');
        $levels = Levels::where('course_id', '=', $course_id)->get();
        return Response::json($levels);
    }


    /**
     * Show the form for creating a new ClassScheduling.
     *
     * @return Response
     */
    public function create()
    {
        return view('class_schedulings.create');
    }

    /**
     * Store a newly created ClassScheduling in storage.
     *
     * @param CreateClassSchedulingRequest $request
     *
     * @return Response
     */
    public function store(CreateClassSchedulingRequest $request)
    {
        $input = $request->all();

        $classScheduling = $this->classSchedulingRepository->create($input);

        Flash::success('Class Scheduling saved successfully.');

        return redirect(route('classSchedulings.index'));
    }

    /**
     * Display the specified ClassScheduling.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $classScheduling = $this->classSchedulingRepository->find($id);

        if (empty($classScheduling)) {
            Flash::error('Class Scheduling not found');

            return redirect(route('classSchedulings.index'));
        }

        return view('class_schedulings.show')->with('classScheduling', $classScheduling);
    }

    /**
     * Show the form for editing the specified ClassScheduling.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $batch = Batch::all();
        $class = Classes::all();
        $classrooms = Classrooms::all();
        $course = Course::all();
        $day = Day::all();
        $level = Levels::all();
        $semester = Semester::all();
        $shift = Shift::all();
        $time = Time::all();

        $classScheduling = $this->classSchedulingRepository->find($id);

        $classshedule = DB::table('class_schedulings')->select(
            'courses.*',
            'levels.*',
            'days.*',
            'batches.*',
            'semesters.*',
            'classes.*',
            'shifts.*',
            'times.*',
            'classrooms.*',
            'class_schedulings.*'
            )
            ->whereNull('class_schedulings.deleted_at')
            ->join('courses','courses.course_id', '=', 'class_schedulings.course_id') 
            ->join('batches','batches.batch_id', '=', 'class_schedulings.batch_id')
            ->join('classes','classes.class_id', '=', 'class_schedulings.class_id')
            ->join('days','days.day_id', '=', 'class_schedulings.day_id')
            ->join('levels','levels.id', '=', 'class_schedulings.level_id')
            ->join('semesters','semesters.semesters_id', '=', 'class_schedulings.semester_id')
            ->join('shifts','shifts.shift_id', '=', 'class_schedulings.shift_id')
            ->join('times','times.time_id', '=', 'class_schedulings.time_id')
            ->join('classrooms','classrooms.classroom_id', '=', 'class_schedulings.classroom_id')
            ->get();
            //dd($classshedule); die;

        if (empty($classScheduling)) {
            Flash::error('Class Scheduling not found');

            return redirect(route('classSchedulings.index'));
        }

        return view('class_schedulings.edit', compact('classshedule','batch','class','classrooms','course','day','level','semester','shift','time'))
        ->with('classScheduling', $classScheduling);
    }

    /**
     * Update the specified ClassScheduling in storage.
     *
     * @param int $id
     * @param UpdateClassSchedulingRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateClassSchedulingRequest $request)
    {
        $classScheduling = $this->classSchedulingRepository->find($id);

        if (empty($classScheduling)) {
            Flash::error('Class Scheduling not found');

            return redirect(route('classSchedulings.index'));
        }

        $classScheduling = $this->classSchedulingRepository->update($request->all(), $id);

        Flash::success('Class Scheduling updated successfully.');

        return redirect(route('classSchedulings.index'));
    }

    /**
     * Remove the specified ClassScheduling from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $classScheduling = $this->classSchedulingRepository->find($id);

        if (empty($classScheduling)) {
            Flash::error('Class Scheduling not found');

            return redirect(route('classSchedulings.index'));
        }

        $this->classSchedulingRepository->delete($id);

        Flash::success('Class Scheduling deleted successfully.');

        return redirect(route('classSchedulings.index'));
    }
}

resources/views/class_schedulings/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Class Scheduling
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'classSchedulings.store']) !!}

                        @include('class_schedulings.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/class_schedulings/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left fa fa-calendar-check-o"> Class Schedulings</h1>
        <h1 class="pull-right">
           <a data-toggle="modal" data-target="#classschedule-show" class="btn btn-success pull-right" style="margin-top: -10px;margin-bottom: 5px"><i class="fa fa-plus-circle"> Generate New Class Schedule</i></a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')
        @include('adminlte-templates::common.errors')

        <div class="clearfix"></div> 
        <div class="box box-primary">
            <div class="box-body">
                    @include('class_schedulings.table')
                    {!! Form::open(['route' => 'classSchedulings.store']) !!}

                        @include('class_schedulings.fields')

                    {!! Form::close() !!}
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/class_schedulings/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Class Scheduling
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('class_schedulings.show_fields')
                    <a href="{{ route('classSchedulings.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/class_schedulings/show_fields.blade.php
<!-- Course Id Field -->
<div class="form-group">
    {!! Form::label('course_id', 'Course Id:') !!}
    <p>{{ $classScheduling->course_id }}</p>
</div>

<!-- Class Id Field -->
<div class="form-group">
    {!! Form::label('class_id', 'Class Id:') !!}
    <p>{{ $classScheduling->class_id }}</p>
</div>

<!-- Level Id Field -->
<div class="form-group">
    {!! Form::label('level_id', 'Level Id:') !!}
    <p>{{ $classScheduling->level_id }}</p>
</div>

<!-- Shift Id Field -->
<div class="form-group">
    {!! Form::label('shift_id', 'Shift Id:') !!}
    <p>{{ $classScheduling->shift_id }}</p>
</div>

<!-- Classroom Id Field -->
<div class="form-group">
    {!! Form::label('classroom_id', 'Classroom Id:') !!}
    <p>{{ $classScheduling->classroom_id }}</p>
</div>

<!-- Batch Id Field -->
<div class="form-group">
    {!! Form::label('batch_id', 'Batch Id:') !!}
    <p>{{ $classScheduling->batch_id }}</p>
</div>

<!-- Day Id Field -->
<div class="form-group">
    {!! Form::label('day_id', 'Day Id:') !!}
    <p>{{ $classScheduling->day_id }}</p>
</div>

<!-- Time Id Field -->
<div class="form-group">
    {!! Form::label('time_id', 'Time Id:') !!}
    <p>{{ $classScheduling->time_id }}</p>
</div>

<!-- Semester Id Field -->
<div class="form-group">
    {!! Form::label('semester_id', 'Semester Id:') !!}
    <p>{{ $classScheduling->semester_id }}</p>
</div>

<!-- Start Date Field -->
<div class="form-group">
    {!! Form::label('start_date', 'Start Date:') !!}
    <p>{{ $classScheduling->start_date }}</p>
</div>

<!-- End Date Field -->
<div class="form-group">
    {!! Form::label('end_date', 'End Date:') !!}
    <p>{{ $classScheduling->end_date }}</p>
</div>

<!-- Status Field -->
<div class="form-group">
    {!! Form::label('status', 'Status:') !!}
    <p>{{ $classScheduling->status }}</p>
</div>

resources/views/class_schedulings/table.blade.php
<div class="table-responsive">
    <table class="table" id="classSchedulings-table">
        <thead>
            <tr>
                <th>Course Id</th>
        <th>Class</th>
        <th>Level</th>
        {{-- <th>Shift</th>
        <th>Classroom</th>
        <th>Batch</th>
        <th>Day</th>
        <th>Time</th>
        <th>Semester</th>
        <th>Start Date</th>
        <th>End Date</th> --}}
        <th>Status</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($classshedule as $classScheduling)
            <tr>
                <td>{{ $classScheduling->course_name }}</td>
                <td>{{ $classScheduling->class_name }}</td>
                <td>{{ $classScheduling->level }}</td>
                {{-- <td>{{ $classScheduling->shift }}</td>
                <td>{{ $classScheduling->classroom_name }}</td>
                <td>{{ $classScheduling->batch }}</td>
                <td>{{ $classScheduling->name }}</td>
                <td>{{ $classScheduling->time }}</td>
                <td>{{ $classScheduling->semesters_name }}</td>
                <td>{{ $classScheduling->show_start_date }}</td>
                <td>{{ $classScheduling->show_end_date }}</td> --}}
                <td>
                    @if ($classScheduling->status == 1)
                        {{-- <div class="btn btn-success btn-sm">Active</div> --}}
                        <i class="fa fa-check success-mine" aria-hidden="true"> Active</i>
                    @else
                        {{-- <div class="btn btn-danger btn-sm">In-Active</div> --}}
                        <i class="fa fa-times danger-mine" aria-hidden="true"> In-Active</i>
                    @endif
                </td>
                <td>
                    {!! Form::open(['route' => ['classSchedulings.destroy', $classScheduling->schedule_id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a data-toggle="modal" data-target="#schedule-view-modal" data-show_schedule_id="{{ $classScheduling->schedule_id }}" data-show_course_id="{{ $classScheduling->course_name }}"  data-show_class_id="{{ $classScheduling->class_name }}" data-show_level_id="{{ $classScheduling->level }}"  data-show_shift_id="{{ $classScheduling->shift }}"  data-show_classroom_id="{{ $classScheduling->classroom_name }}"  data-show_batch_id="{{ $classScheduling->batch }}"  data-show_day_id="{{ $classScheduling->name }}"  data-show_time_id="{{ $classScheduling->time }}"  data-show_semester_id="{{ $classScheduling->semesters_name }} - {{ $classScheduling->semesters_code }}"  data-show_start_date="{{ $classScheduling->start_date }}" data-show_end_date="{{ $classScheduling->end_date }}"  data-show_created_at="{{ $classScheduling->created_at }}" data-show_updated_at="{{ $classScheduling->updated_at }}"  
                            @if ($classScheduling->status == 1)
                            data-show_status="Active" 
                            @else
                                data-show_status="In-Active" 
                            @endif  
                        class='btn btn-default btn-xs margin-mine'><i class="glyphicon glyphicon-eye-open"></i> View Details</a>
                        
                        {{-- <a href="{{ route('classSchedulings.show', [$classScheduling->schedule_id]) }}" class='btn btn-default btn-xs margin-mine'><i class="glyphicon glyphicon-eye-open"></i></a> --}}

                        <a href="{{ route('classSchedulings.edit', [$classScheduling->schedule_id]) }}" class='btn btn-default btn-xs margin-mine'><i class="glyphicon glyphicon-edit"></i> Edit Details</a>

                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i> Delete Details', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

<!--SHOW Modal -->
<div class="modal fade" id="schedule-view-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel"><i class="fa fa-calendar-check-o" aria-hidden="true"></i> Class Scheduling</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body"><!-- Batch Field -->

                <input type="hidden" name="show_schedule_id" id="show_schedule_id">
               
                <!-- Class Id Field -->
                <div class="form-group col-sm-6">
                    {!! Form::label('class_id', 'Class Id:') !!}
                    {{-- {!! Form::number('class_id', null, ['class' => 'form-control']) !!} --}}
                    <input type="text" name="show_class_id" id="show_class_id" readonly>
                </div>

                <!-- Course Id Field -->
                <div class="form-group col-sm-12">
                    {!! Form::label('show_course_id', 'Course Id:') !!}
                    {{-- {!! Form::number('show_course_id', null, ['class' => 'form-control']) !!} --}}
                    <input type="text" size="100" name="show_course_id" id="show_course_id" readonly>

                </div>

                <!-- Level Id Field -->
                <div class="form-group col-sm-6">
                    {!! Form::label('show_level_id', 'Level Id:') !!}
                    {{-- {!! Form::number('show_level_id', null, ['class' => 'form-control']) !!} --}}
                    <input type="text" name="show_level_id" id="show_level_id" readonly>
                </div>

                <!-- Shift Id Field -->
                <div class="form-group col-sm-6">
                    {!! Form::label('show_shift_id', 'Shift Id:') !!}
                    {{-- {!! Form::number('show_shift_id', null, ['class' => 'form-control']) !!} --}}
                    <input type="text" name="show_shift_id" id="show_shift_id" readonly>

                </div>

                <!-- Classroom Id Field -->
                <div class="form-group col-sm-6">
                    {!! Form::label('show_classroom_id', 'Classroom Id:') !!}
                    {{-- {!! Form::number('show_classroom_id', null, ['class' => 'form-control']) !!} --}}
                    <input type="text" name="show_classroom_id" id="show_classroom_id" readonly>
                </div>

                <!-- Batch Id Field -->
                <div class="form-group col-sm-6">
                    {!! Form::label('show_batch_id', 'Batch Id:') !!}
                    {{-- {!! Form::number('show_batch_id', null, ['class' => 'form-control']) !!} --}}
                    <input type="text" name="show_batch_id" id="show_batch_id" readonly>
                </div>

                <!-- Day Id Field -->
                <div class="form-group col-sm-6">
                    {!! Form::label('show_day_id', 'Day Id:') !!}
                    {{-- {!! Form::number('show_day_id', null, ['class' => 'form-control']) !!} --}}
                    <input type="text" name="show_day_id" id="show_day_id" readonly>
                </div>

                <!-- Time Id Field -->
                <div class="form-group col-sm-6">
                    {!! Form::label('show_time_id', 'Time Id:') !!}
                    {{-- {!! Form::number('show_time_id', null, ['class' => 'form-control']) !!} --}}
                    <input type="text" name="show_time_id" id="show_time_id" readonly>
                </div>

                <!-- Semester Id Field -->
                <div class="form-group col-sm-6">
                    {!! Form::label('show_semester_id', 'Semester Id:') !!}
                    {{-- {!! Form::number('show_semester_id', null, ['class' => 'form-control']) !!} --}}
                    <input type="text" name="show_semester_id" id="show_semester_id" readonly>
                </div>

                <!-- Start Date Field -->
                <div class="form-group col-sm-6">
                    {!! Form::label('show_start_date', 'Start Date:') !!}
                    <input type="text" name="show_start_date" id="show_start_date" readonly>
                </div>

                <!-- End Date Field -->
                <div class="form-group col-sm-6">
                    {!! Form::label('show_end_date', 'End Date:') !!}
                    <input type="text" name="show_end_date" id="show_end_date" readonly>
                </div>

                <!-- show_status Field -->
                <div class="form-group col-sm-6">
                    {!! Form::label('show_status', 'Status:') !!}
                    <input type="text" name="show_status" id="show_status" readonly>
                </div>

                <!-- Created At Field -->
                <div class="form-group col-sm-6">
                    {!! Form::label('created_at', 'Created At:') !!}
                    <input type="text" name="show_created_at" id="show_created_at" readonly>
                </div>

                <!-- Updated At Field -->
                <div class="form-group col-sm-6">
                    {!! Form::label('updated_at', 'Updated At:') !!}
                    <input type="text" name="show_updated_at" id="show_updated_at" readonly>
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section('script')
    <script>
        $('#schedule-view-modal').on('show.bs.modal',function (event) {
            var button = $(event.relatedTarget)
            var show_class_id = button.data('show_class_id')
            var show_course_id = button.data('show_course_id')
            var show_level_id = button.data('show_level_id')
            var show_shift_id = button.data('show_shift_id')
            var show_classroom_id = button.data('show_classroom_id')
            var show_batch_id = button.data('show_batch_id')
            var show_day_id = button.data('show_day_id')
            var show_time_id = button.data('show_time_id')
            var show_semester_id = button.data('show_semester_id')
            var show_start_date = button.data('show_start_date')
            var show_end_date = button.data('show_end_date')
            var show_status = button.data('show_status')
            var show_created_at = button.data('show_created_at')
            var show_updated_at = button.data('show_updated_at')
            var show_schedule_id = button.data('show_schedule_id')

            var modal = $(this)

            // modal.find('.modal-title').text('View Batch Information');
            modal.find('.modal-body #show_class_id').val(show_class_id);
            modal.find('.modal-body #show_course_id').val(show_course_id);
            modal.find('.modal-body #show_level_id').val(show_level_id);
            modal.find('.modal-body #show_shift_id').val(show_shift_id);
            modal.find('.modal-body #show_classroom_id').val(show_classroom_id);
            modal.find('.modal-body #show_batch_id').val(show_batch_id);
            modal.find('.modal-body #show_day_id').val(show_day_id);
            modal.find('.modal-body #show_time_id').val(show_time_id);
            modal.find('.modal-body #show_semester_id').val(show_semester_id);
            modal.find('.modal-body #show_start_date').val(show_start_date);
            modal.find('.modal-body #show_end_date').val(show_end_date);
            modal.find('.modal-body #show_status').val(show_status);
            modal.find('.modal-body #show_created_at').val(show_created_at);
            modal.find('.modal-body #show_updated_at').val(show_updated_at);
            modal.find('.modal-body #show_schedule_id').val(show_schedule_id);
        });
    </script>
@endsection